export const SERVICES_REQUEST = 'SERVICES_REQUEST';
export const SERVICES_FAILURE = 'SERVICES_FAILURE';
export const SERVICES_SUCCESS = 'SERVICES_SUCCESS';
export const SELECTED_SERVICES_REQUEST = 'SELECTED_SERVICES_REQUEST';
export const SELECTED_SERVICES_FAILURE = 'SELECTED_SERVICES_FAILURE';
export const SELECTED_SERVICES_SUCCESS = 'SELECTED_SERVICES_SUCCESS';
